---
title: "Conjoint Analysis"
---

## Introduction

Discrete choice models enable market researchers to make predictions on what kinds of products might have the best chance to succeed in the market. The advantage that choice methods have in market research is that you can strategically ask survey respondents to make choices on products they would buy and then infer their preferences based on the choices they made. An exercise like this is more intuitive and more likely to reflect a respondent's actual behaviour. We can't replicate the in-store experience, but asking someone "how likely would you be to buy this product?" directly can often be tough for respondents to accurately judge.

These choice models take many different forms, but one common type in market research is `conjoint` analysis. The conjoint analysis technique proposes that products are broken down to components or main features, which can then vary randomly among a set of options. By building sets of options with strategic, or random, variations and asking survey respondents to say which (if any) they would purchase on a shopping trip we can model the choices to determine a valuation for each component. Then we can use those results to optimize product offering to give them the best chance to get attention from customers.


[`formr`](https://formr.org) offers an interesting interface to build and run surveys with `R`. Because it leverages `R` code, you can run code chunks within a survey, which allows us to do a lot of interesting things with experimental designs and choice experiments, we consider a conjoint exercise in here.

----


## formr

To use [`formr`](https://formr.org), sign up on their website and request an admin token from the developers. This admin token allows you to set up surveys by specifying questions in a Google Sheet or .xlsx document. They provide an example demo of question types [here](https://formr.org/documentation#sample_survey_sheet).


----

## Design

Choice methodologies are constructed as an experiment, where we ask respondents to consider a set of alternatives and choose their favourite or what they would buy on a shopping trip. As we attempt to build a random utility maximization model around the components of products, we want our model to be able to disentangle the values of various components by building an efficient design.


